# Generated by Django 5.2.7 on 2025-10-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name='الرابط الفرعي (Slug)'),
        ),
    ]
