# Generated by Django 5.2.7 on 2025-10-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_colors',
            field=models.CharField(default='Pink,Blue,Black', help_text='Enter colors separated by comma (e.g., Pink,Blue,Black)', max_length=255, verbose_name='الألوان المتاحة'),
        ),
        migrations.AddField(
            model_name='product',
            name='available_sizes',
            field=models.CharField(default='S,M,L,XL', help_text='Enter sizes separated by comma (e.g., S,M,L,XL)', max_length=255, verbose_name='المقاسات المتاحة'),
        ),
    ]
